import numpy as np                               #type: ignore
import trimesh                                   #type: ignore
from mesh_to_sdf import sample_sdf_near_surface  #type: ignore


def generate_point_cloud(mesh,num_points):

    """
    Function to generate a point cloud from a mesh using the mesh_to_sdf library.
    The point cloud is generated by sampling points near the surface of the mesh and computing the signed distance function (SDF) values and gradients at those points.

    input: 
    mesh: trimesh object representing the 3D mesh
    num_points: number of points to sample in the point cloud

    output:
    point_cloud_data: numpy array of shape (num_points, 7) containing the x, y, z coordinates of the points, SDF values, and gradients 
         Column 0 --> x-coordinates
         Column 1 --> y-coordinates
         Column 2 --> z-coordinates
         Column 3 --> SDF values
         Column 4 --> gradient x-component = dx
         Column 5 --> gradient y-component = dy
         Column 6 --> gradient z-component = dz
         Gradient vector = [dx, dy, dz]
    """
    # Extract information needed to re-scale the point cloud --> point cloud is normalized to fit inside the unit sphere and needs to be re-scaled to the original mesh size
    center = mesh.bounding_box.centroid
    radius = np.max(np.linalg.norm(mesh.vertices - center, axis=1))

    # Generate the point cloud using the mesh_to_sdf library 
    points, sdf , gradients = sample_sdf_near_surface(     mesh, 
                                      number_of_points     = num_points, 
                                      scan_resolution      = 1000,
                                      return_gradients     = True,
                                      surface_point_method = 'scan',
                                      scan_count           = 100,
                                      sign_method          = 'depth')
    
    # Inverse transformation: convert the normalized points and SDF values back to the original scale
    points_original_scale = points * radius + center
    sdf_original_scale = sdf * radius

    # Combine the points, SDF values, and gradients into a single array
    point_cloud_data = np.column_stack((points_original_scale, sdf_original_scale, gradients))

    return point_cloud_data 

"""
Example usage:

from Functions.Data_preprocessing_functions.PointCloud_generation import generate_point_cloud

# Generate a point cloud from the mesh
num_points = 250000  
point_cloud_data = generate_point_cloud(Part6_mesh, num_points)

"""